config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  get '/users', to: 'users#index'
  get '/users/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/models/diaryapp.rb
class Diaryapp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:title, :body)
    end
end

app/controllers/diaryapps_controller.rb
class DiaryappsController < ApplicationController
  before_action :set_diaryapp, only: %i[ show edit update destroy ]

  # GET /diaryapps 
  # GET /diaryapps.json
  def index
    @diaryapps = Diaryapp.all
  end

  # GET /diaryapps/1 or /diaryapps/1.json
  def show
  end

  # GET /diaryapps/new
  def new
    @diaryapp = Diaryapp.new
  end

  # GET /diaryapps/1/edit
  def edit
  end

  # POST /diaryapps or /diaryapps.json
  def create
    @diaryapp = Diaryapp.new(diaryapp_params)

    respond_to do |format|
      if @diaryapp.save
        format.html { redirect_to @diaryapp, notice: "Diaryapp was successfully created." }
        format.json { render :show, status: :created, location: @diaryapp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diaryapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaryapps/1 or /diaryapps/1.json
  def update
    respond_to do |format|
      if @diaryapp.update(diaryapp_params)
        format.html { redirect_to @diaryapp, notice: "Diaryapp was successfully updated." }
        format.json { render :show, status: :ok, location: @diaryapp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diaryapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaryapps/1 or /diaryapps/1.json
  def destroy
    @diaryapp.destroy
    respond_to do |format|
      format.html { redirect_to diaryapps_url, notice: "Diaryapp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diaryapp
      @diaryapp = Diaryapp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diaryapp_params
      params.require(:diaryapp).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @hello = 'Hello, world!'
    
    render template: 'users/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diaryapps_helper.rb
module DiaryappsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>日記一覧画面</h1>

<table>

  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.created_at %></td>
        <td><%= diary.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記を新規作成', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @diary.body %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

app/views/diaryapps/_form.html.erb
<%= form_with(model: diaryapp, local: true) do |form| %>
  <% if diaryapp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diaryapp.errors.count, "error") %> prohibited this diaryapp from being saved:</h2>

      <ul>
        <% diaryapp.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaryapps/edit.html.erb
<h1>Editing Diaryapp</h1>

<%= render 'form', diaryapp: @diaryapp %>

<%= link_to 'Show', @diaryapp %> |
<%= link_to 'Back', diaryapps_path %>

app/views/diaryapps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diaryapps</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaryapps.each do |diaryapp| %>
      <tr>
        <td><%= diaryapp.title %></td>
        <td><%= diaryapp.body %></td>
        <td><%= link_to 'Show', diaryapp %></td>
        <td><%= link_to 'Edit', edit_diaryapp_path(diaryapp) %></td>
        <td><%= link_to 'Destroy', diaryapp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diaryapp', new_diaryapp_path %>

app/views/diaryapps/new.html.erb
<h1>New Diaryapp</h1>

<%= render 'form', diaryapp: @diaryapp %>

<%= link_to 'Back', diaryapps_path %>

app/views/diaryapps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @diaryapp.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @diaryapp.body %>
</p>

<%= link_to 'Edit', edit_diaryapp_path(@diaryapp) %> |
<%= link_to 'Back', diaryapps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    ヘッダー
    </header>
    <div>
      <%= yield %>
    </div>
    <footer>
    フッター
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<div><%= @hello %></div>

app/views/users/new.html.erb
<div>
こんにちは日本から世界へ
</div>